"""Release preparation protects destinations, source binding and Git history."""
import importlib.util
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[1]


def module(name, file):
    spec = importlib.util.spec_from_file_location(name, ROOT / file)
    result = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(result)
    return result


class NativeReleaseTest(unittest.TestCase):
    def test_archive_cleanup_requires_recorded_ownership_and_matching_bytes(self):
        builder = module('pd_archive_owner', 'scripts/build-plugin.py')
        with tempfile.TemporaryDirectory(prefix='pd-archive-ownership-') as temporary:
            builder.ROOT = Path(temporary)
            dist = builder.ROOT / 'dist'
            dist.mkdir()
            owned = dist / 'program-design-0.2.0-codex.zip'
            owned.write_bytes(b'old generated bytes')
            backup = dist / 'program-design-backup-codex.zip'
            backup.write_bytes(b'user backup')
            manifest = {'product': 'program-design', 'version': '0.2.0', 'platforms': {
                'codex': {'archive': owned.name, 'sha256': builder.sha(owned.read_bytes())}}}
            (dist / 'manifest.json').write_text(json.dumps(manifest))
            self.assertEqual(builder.retired_archives(), [owned])
            self.assertEqual(backup.read_bytes(), b'user backup')
            owned.write_bytes(b'user changed archive')
            with self.assertRaisesRegex(ValueError, 'Modified legacy archive preserved'):
                builder.retired_archives()
            self.assertEqual(owned.read_bytes(), b'user changed archive')
            (dist / 'manifest.json').write_text(json.dumps({'schema_version': 2, 'product': 'program-design'}))
            self.assertEqual(builder.retired_archives(), [])

    def test_bad_release_arguments_fail_before_creating_output(self):
        with tempfile.TemporaryDirectory(prefix='pd-release-args-') as temporary:
            output = Path(temporary) / 'must-not-exist'
            base = [sys.executable, str(ROOT / 'scripts/prepare-native-release.py'), '--output', str(output)]
            for arguments in [
                ['--npm-scope', 'scope'],
                ['--repository-url', 'https://user:secret@example.invalid/repo', '--npm-scope', 'scope'],
                ['--repository-url', 'https://example.invalid/repo', '--npm-scope', '../escape'],
                ['--previous-release', str(Path(temporary) / 'missing')],
            ]:
                with self.subTest(arguments=arguments):
                    result = subprocess.run(base + arguments, capture_output=True, text=True)
                    self.assertEqual(result.returncode, 2, result.stderr)
                    self.assertFalse(output.exists())
            output.mkdir()
            (output / 'user-file').write_text('preserve')
            result = subprocess.run(base, capture_output=True, text=True)
            self.assertEqual(result.returncode, 2)
            self.assertEqual((output / 'user-file').read_text(), 'preserve')

    def test_stale_typescript_and_tampered_compiler_output_are_rejected(self):
        builder = module('pd_release_builder', 'scripts/build-plugin.py')
        original, upstream = builder.read_upstream()
        files = builder.distributions(builder.transform(original), upstream, compiled=False)['opencode']
        valid = dict(files)
        builder.attach_opencode_compiled(valid)
        self.assertIn('dist/index.js', valid)
        files['src/core.ts'] = (files['src/core.ts'][0] + b'\n// changed source\n', 0o644)
        with self.assertRaisesRegex(ValueError, 'stale'):
            builder.attach_opencode_compiled(files)
        with tempfile.TemporaryDirectory(prefix='pd-compiled-tamper-') as temporary:
            overlay = Path(temporary)
            shutil.copytree(ROOT / 'overlays/program-design/opencode-compiled', overlay / 'opencode-compiled')
            (overlay / 'opencode-compiled/dist/index.js').write_text('changed compiled code')
            builder.OVERLAY = overlay
            with self.assertRaisesRegex(ValueError, 'digest mismatch'):
                builder.attach_opencode_compiled(valid)

    @unittest.skipUnless(shutil.which('git'), 'Git required for release branch continuity')
    def test_git_release_tree_preserves_lineage_and_removes_old_files(self):
        builder = module('pd_git_release_builder', 'scripts/build-plugin.py')
        release = module('pd_release', 'scripts/prepare-native-release.py')
        with tempfile.TemporaryDirectory(prefix='pd-release-history-') as temporary:
            root = Path(temporary)
            profile = root / 'profile'
            profile.mkdir()
            env = {'PATH': os.environ['PATH'], 'HOME': str(profile), 'GIT_CONFIG_GLOBAL': os.devnull,
                   'GIT_CONFIG_NOSYSTEM': '1', 'GIT_AUTHOR_DATE': '2000-01-01T00:00:00Z',
                   'GIT_COMMITTER_DATE': '2000-01-01T00:00:00Z'}
            a, b = root / 'A', root / 'B'
            a.mkdir()
            b.mkdir()
            first = {'gemini-extension.json': (b'{"name":"program-design","version":"0.3.0"}\n', 0o644),
                     'changed.txt': (b'A', 0o644), 'removed.txt': (b'old', 0o644)}
            second = {**first, 'changed.txt': (b'B', 0o644), 'added.txt': (b'new', 0o755)}
            del second['removed.txt']
            old = release.git_tree(builder, 'gemini', first, a, None, env)
            new = release.git_tree(builder, 'gemini', second, b, a, env)
            target = b / 'git/gemini'
            parent = release.run(['git', 'rev-parse', 'HEAD^'], target, env)
            self.assertEqual(parent, old['commit'])
            self.assertNotEqual(old['commit'], new['commit'])
            self.assertEqual((target / 'changed.txt').read_bytes(), b'B')
            self.assertFalse((target / 'removed.txt').exists())
            self.assertTrue((target / 'added.txt').stat().st_mode & 0o111)
            self.assertEqual(release.run(['git', 'remote'], target, env), '')
            self.assertEqual(release.run(['git', 'status', '--porcelain'], target, env), '')


if __name__ == '__main__':
    unittest.main()
